###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/chamados
Content-Type: application/json

{
    "titulo": "PC não Liga",
    "descricao": "Algo de incorreto está ocorrendo",
    "usuario_id": "1"
}

###

