###

GET http://localhost:3000/usuarios/

###

POST http://localhost:3000/chamados
Content-Type: application/json

{
    "titulo": "PC não Ligaaaaadsasda",
    "descricao": "Algo de incorreto está ocorrendo",
    "usuario_id": "1"
}

###

###

POST http://localhost:3000//usuarios
Content-Type: application/json

{
    "nome": "Gui1",
    "email": "gui@estudante.com",
    "senha": "paocomqueijo"
}

###

DELETE http://localhost:3000/chamados/1

###

###

PUT http://localhost:3000/chamados/3
Content-Type:application/json

{
    "titulo": "asdadas",
    "descricao": "dasdasdasd"
}

###